name: Build Android APK

on:
  push:
    branches:
      - android-apk

jobs:
  build_android_apk:
    type: build
    params:
      platform: android
      profile: apk
      message: build pipeline from branch android-apk
